apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "planemgr.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "planemgr.name" . }}
    app.kubernetes.io/component: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "planemgr.name" . }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "planemgr.name" . }}
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.service.port }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
